### ISSUE TITLE
"Can only update a mounted or mounting component..."

### ISSUE THREAD

**Issue by catemlitten** [ELEVATORmedia/axlry#29]
![error1](https://user-images.githubusercontent.com/28066928/34645664-5299eb82-f319-11e7-840c-3fc40fb6a8e9.png)

Showed on account creation login. Did not reproduce on second login.

**Comment by dallen4** [comment]
@catemlitten was this fixed with the overhaul to RNFirebase?

**Comment by dallen4** [comment]
Fixed with rollover to RNFirebase. Closing.
